import "./globals.css";
import Footer from "../../Footer";
import NavBar from "../../NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-TTGWBZG8"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript>
        <NavBar />
        <div className="flex flex-col flex-[1_0_auto]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
